name = "video-upload-interface"
compatibility_date = "2024-03-14"
compatibility_flags = ["nodejs_compat"]

[build]
command = "npm run pages:build"

## For Wrangler Pages, specify the output dir at the top level
pages_build_output_dir = ".vercel/output/static"

[pages]
# Redundant but ensures Pages deploys pick these up
build_output_dir = ".vercel/output/static"
compatibility_flags = ["nodejs_compat_populate_process_env"]

[vars]
NODE_VERSION = "18"

[dev]
port = 8788
